/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasgui;

/**
 *
 * @author Nurus Laily
 */
public class Kalkulator_1841720049Nurus extends javax.swing.JFrame {
        float n, hasil;
        String operasi;
    /**
     * Creates new form Kalkulator_1841720049Nurus
     */
    public Kalkulator_1841720049Nurus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HasilNurus = new javax.swing.JTextField();
        TujuhNurus = new javax.swing.JButton();
        DelapanNurus = new javax.swing.JButton();
        SembilanNurus = new javax.swing.JButton();
        BagiNurus = new javax.swing.JButton();
        EmpatNurus = new javax.swing.JButton();
        LimaNurus = new javax.swing.JButton();
        EnamNurus = new javax.swing.JButton();
        KaliNurus = new javax.swing.JButton();
        SatuNurus = new javax.swing.JButton();
        DuaNurus = new javax.swing.JButton();
        TigaNurus = new javax.swing.JButton();
        KurangNurus = new javax.swing.JButton();
        NolNurus = new javax.swing.JButton();
        KomaNurus = new javax.swing.JButton();
        TambahNurus = new javax.swing.JButton();
        SamadenganNurus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HasilNurus.setText("0");
        HasilNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilNurusActionPerformed(evt);
            }
        });

        TujuhNurus.setText("7");
        TujuhNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TujuhNurusActionPerformed(evt);
            }
        });

        DelapanNurus.setText("8");
        DelapanNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelapanNurusActionPerformed(evt);
            }
        });

        SembilanNurus.setText("9");
        SembilanNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SembilanNurusActionPerformed(evt);
            }
        });

        BagiNurus.setText("/");
        BagiNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagiNurusActionPerformed(evt);
            }
        });

        EmpatNurus.setText("4");
        EmpatNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpatNurusActionPerformed(evt);
            }
        });

        LimaNurus.setText("5");
        LimaNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimaNurusActionPerformed(evt);
            }
        });

        EnamNurus.setText("6");
        EnamNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnamNurusActionPerformed(evt);
            }
        });

        KaliNurus.setText("*");
        KaliNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaliNurusActionPerformed(evt);
            }
        });

        SatuNurus.setText("1");
        SatuNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatuNurusActionPerformed(evt);
            }
        });

        DuaNurus.setText("2");
        DuaNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuaNurusActionPerformed(evt);
            }
        });

        TigaNurus.setText("3");
        TigaNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TigaNurusActionPerformed(evt);
            }
        });

        KurangNurus.setText("-");
        KurangNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KurangNurusActionPerformed(evt);
            }
        });

        NolNurus.setText("0");
        NolNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NolNurusActionPerformed(evt);
            }
        });

        KomaNurus.setText(".");
        KomaNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KomaNurusActionPerformed(evt);
            }
        });

        TambahNurus.setText("+");
        TambahNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahNurusActionPerformed(evt);
            }
        });

        SamadenganNurus.setText("=");
        SamadenganNurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamadenganNurusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SamadenganNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NolNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SatuNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EmpatNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TujuhNurus, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DelapanNurus, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LimaNurus, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DuaNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EnamNurus, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TigaNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SembilanNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KomaNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(KaliNurus, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BagiNurus, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KurangNurus, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TambahNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(HasilNurus))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HasilNurus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DelapanNurus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(TujuhNurus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BagiNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SembilanNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LimaNurus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpatNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KaliNurus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnamNurus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SatuNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DuaNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KurangNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TigaNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NolNurus, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(KomaNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TambahNurus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SamadenganNurus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HasilNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilNurusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilNurusActionPerformed

    private void TujuhNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TujuhNurusActionPerformed
        // TODO add your handling code here:
        HasilNurus.setText(HasilNurus.getText()+"7");
    }//GEN-LAST:event_TujuhNurusActionPerformed

    private void DelapanNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelapanNurusActionPerformed
        // TODO add your handling code here:
        HasilNurus.setText(HasilNurus.getText()+"8");
    }//GEN-LAST:event_DelapanNurusActionPerformed

    private void SembilanNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SembilanNurusActionPerformed
        // TODO add your handling code here:
        HasilNurus.setText(HasilNurus.getText()+"9");
    }//GEN-LAST:event_SembilanNurusActionPerformed

    private void BagiNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagiNurusActionPerformed
        // TODO add your handling code here:
        n =Float.parseFloat(HasilNurus.getText());
        operasi="bagi";
        HasilNurus.setText("");
    }//GEN-LAST:event_BagiNurusActionPerformed

    private void EmpatNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpatNurusActionPerformed
        // TODO add your handling code here:
        HasilNurus.setText(HasilNurus.getText()+"4");
    }//GEN-LAST:event_EmpatNurusActionPerformed

    private void LimaNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimaNurusActionPerformed
        // TODO add your handling code here:
        HasilNurus.setText(HasilNurus.getText()+"5");
    }//GEN-LAST:event_LimaNurusActionPerformed

    private void EnamNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnamNurusActionPerformed
        // TODO add your handling code here:
        HasilNurus.setText(HasilNurus.getText()+"6");
    }//GEN-LAST:event_EnamNurusActionPerformed

    private void KaliNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaliNurusActionPerformed
        // TODO add your handling code here:
        n =Float.parseFloat(HasilNurus.getText());
        operasi="kali";
        HasilNurus.setText("");
    }//GEN-LAST:event_KaliNurusActionPerformed

    private void SatuNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatuNurusActionPerformed
        // TODO add your handling code here:
        HasilNurus.setText(HasilNurus.getText()+"1");
    }//GEN-LAST:event_SatuNurusActionPerformed

    private void DuaNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuaNurusActionPerformed
        // TODO add your handling code here:
        HasilNurus.setText(HasilNurus.getText()+"2");
    }//GEN-LAST:event_DuaNurusActionPerformed

    private void TigaNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TigaNurusActionPerformed
        // TODO add your handling code here:
        HasilNurus.setText(HasilNurus.getText()+"3");
    }//GEN-LAST:event_TigaNurusActionPerformed

    private void KurangNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KurangNurusActionPerformed
        // TODO add your handling code here:
        n =Float.parseFloat(HasilNurus.getText());
        operasi="kurang";
        HasilNurus.setText("");
    }//GEN-LAST:event_KurangNurusActionPerformed

    private void NolNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NolNurusActionPerformed
        // TODO add your handling code here:
        HasilNurus.setText(HasilNurus.getText()+"0");
    }//GEN-LAST:event_NolNurusActionPerformed

    private void KomaNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KomaNurusActionPerformed
        // TODO add your handling code here:
        HasilNurus.setText(HasilNurus.getText()+".");
    }//GEN-LAST:event_KomaNurusActionPerformed

    private void TambahNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahNurusActionPerformed
        // TODO add your handling code here:
        n =Float.parseFloat(HasilNurus.getText());
        operasi="tambah";
        HasilNurus.setText("");
    }//GEN-LAST:event_TambahNurusActionPerformed

    private void SamadenganNurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamadenganNurusActionPerformed
        // TODO add your handling code here:
        if(operasi=="kali"){
            HasilNurus.setText(Float.toString(n*Float.parseFloat(HasilNurus.getText())));
        }else if(operasi=="bagi"){
            HasilNurus.setText(Float.toString(n/Float.parseFloat(HasilNurus.getText())));
        }else if(operasi=="tambah"){
            HasilNurus.setText(Float.toString(n+Float.parseFloat(HasilNurus.getText())));
        }else if(operasi=="kurang"){
            HasilNurus.setText(Float.toString(n-Float.parseFloat(HasilNurus.getText())));
        }
    }//GEN-LAST:event_SamadenganNurusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator_1841720049Nurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator_1841720049Nurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator_1841720049Nurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator_1841720049Nurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator_1841720049Nurus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BagiNurus;
    private javax.swing.JButton DelapanNurus;
    private javax.swing.JButton DuaNurus;
    private javax.swing.JButton EmpatNurus;
    private javax.swing.JButton EnamNurus;
    private javax.swing.JTextField HasilNurus;
    private javax.swing.JButton KaliNurus;
    private javax.swing.JButton KomaNurus;
    private javax.swing.JButton KurangNurus;
    private javax.swing.JButton LimaNurus;
    private javax.swing.JButton NolNurus;
    private javax.swing.JButton SamadenganNurus;
    private javax.swing.JButton SatuNurus;
    private javax.swing.JButton SembilanNurus;
    private javax.swing.JButton TambahNurus;
    private javax.swing.JButton TigaNurus;
    private javax.swing.JButton TujuhNurus;
    // End of variables declaration//GEN-END:variables
}
